### ISSUE TITLE
Use tab settings from VS Code

### ISSUE THREAD

**Issue by asbjornu** [supperchong/pretty-json#1]
Thanks for this extension! PrettyJson seems to be using tabs for indentation regardless of Visual Studio's settings. Would it be possible to use Visual Studio Code's tab settings, so when `Spaces: 4` is configured, spaces are used on configuration instead of tabs?

**Comment by supperchong** [comment]
good suggestion! I will realize it soon.

**Comment by supperchong** [comment]
[new version](https://marketplace.visualstudio.com/items?itemName=supperchong.pretty-json#review-details) has released.

**Comment by asbjornu** [comment]
Perfect, thanks! 👏
